In [26]:
import numpy as np
docs = [
    'go pakistan',
    'pakistan zindabad',
    'hip hip hurray',
    'jeetega bhai jeetega pakistan jeetega',
    'pakistan ki shaan',
    'lahore lahore',
    'karachi karachi',
    'islamabad islamabad',
    'imran khan zindabad',
    'inquilab zindabad'
]

In [27]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [28]:
tokenizer.fit_on_texts(docs)

In [29]:
len(tokenizer.word_index)

15

In [30]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[8, 1],
 [1, 2],
 [4, 4, 9],
 [3, 10, 3, 1, 3],
 [1, 11, 12],
 [5, 5],
 [6, 6],
 [7, 7],
 [13, 14, 2],
 [15, 2]]

In [31]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 8,  1,  0,  0,  0],
       [ 1,  2,  0,  0,  0],
       [ 4,  4,  9,  0,  0],
       [ 3, 10,  3,  1,  3],
       [ 1, 11, 12,  0,  0],
       [ 5,  5,  0,  0,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [13, 14,  2,  0,  0],
       [15,  2,  0,  0,  0]], dtype=int32)

In [32]:
model = Sequential()
model.add(Embedding(17,output_dim=2,input_length=5))

model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [33]:
model.compile('adam','accuracy')

In [34]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step
[[[ 0.00284959  0.03143441]
  [ 0.03460909  0.02946204]
  [-0.02261049  0.00517107]
  [-0.02261049  0.00517107]
  [-0.02261049  0.00517107]]

 [[ 0.03460909  0.02946204]
  [ 0.00699691 -0.01073499]
  [-0.02261049  0.00517107]
  [-0.02261049  0.00517107]
  [-0.02261049  0.00517107]]

 [[ 0.00714288  0.01153817]
  [ 0.00714288  0.01153817]
  [ 0.04423164  0.0381978 ]
  [-0.02261049  0.00517107]
  [-0.02261049  0.00517107]]

 [[-0.04121704  0.0039677 ]
  [ 0.03981186  0.03312445]
  [-0.04121704  0.0039677 ]
  [ 0.03460909  0.02946204]
  [-0.04121704  0.0039677 ]]

 [[ 0.03460909  0.02946204]
  [-0.00698922 -0.02223337]
  [-0.02390891  0.02177281]
  [-0.02261049  0.00517107]
  [-0.02261049  0.00517107]]

 [[ 0.03331942  0.01144508]
  [ 0.03331942  0.01144508]
  [-0.02261049  0.00517107]
  [-0.02261049  0.00517107]
  [-0.02261049  0.00517107]]

 [[ 0.0423291   0.04529735]
  [ 0.0423291   0.04529735]
  [-0.02261049  0.00517107]
  [-0.02261049  0.0051710